// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Flat messages
type GetRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetResponse struct {
	Details              []byte   `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

type SendJsonRequest struct {
	UserID               string          `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Details              *_struct.Struct `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendJsonRequest) Reset()         { *m = SendJsonRequest{} }
func (m *SendJsonRequest) String() string { return proto.CompactTextString(m) }
func (*SendJsonRequest) ProtoMessage()    {}
func (*SendJsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *SendJsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJsonRequest.Unmarshal(m, b)
}
func (m *SendJsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJsonRequest.Marshal(b, m, deterministic)
}
func (m *SendJsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJsonRequest.Merge(m, src)
}
func (m *SendJsonRequest) XXX_Size() int {
	return xxx_messageInfo_SendJsonRequest.Size(m)
}
func (m *SendJsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendJsonRequest proto.InternalMessageInfo

func (m *SendJsonRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SendJsonRequest) GetDetails() *_struct.Struct {
	if m != nil {
		return m.Details
	}
	return nil
}

type SendJsonResponse struct {
	Details              string   `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJsonResponse) Reset()         { *m = SendJsonResponse{} }
func (m *SendJsonResponse) String() string { return proto.CompactTextString(m) }
func (*SendJsonResponse) ProtoMessage()    {}
func (*SendJsonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SendJsonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJsonResponse.Unmarshal(m, b)
}
func (m *SendJsonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJsonResponse.Marshal(b, m, deterministic)
}
func (m *SendJsonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJsonResponse.Merge(m, src)
}
func (m *SendJsonResponse) XXX_Size() int {
	return xxx_messageInfo_SendJsonResponse.Size(m)
}
func (m *SendJsonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJsonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendJsonResponse proto.InternalMessageInfo

func (m *SendJsonResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type SendJsonStringRequest struct {
	Details              string   `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJsonStringRequest) Reset()         { *m = SendJsonStringRequest{} }
func (m *SendJsonStringRequest) String() string { return proto.CompactTextString(m) }
func (*SendJsonStringRequest) ProtoMessage()    {}
func (*SendJsonStringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SendJsonStringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJsonStringRequest.Unmarshal(m, b)
}
func (m *SendJsonStringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJsonStringRequest.Marshal(b, m, deterministic)
}
func (m *SendJsonStringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJsonStringRequest.Merge(m, src)
}
func (m *SendJsonStringRequest) XXX_Size() int {
	return xxx_messageInfo_SendJsonStringRequest.Size(m)
}
func (m *SendJsonStringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJsonStringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendJsonStringRequest proto.InternalMessageInfo

func (m *SendJsonStringRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type SendJsonStringResponse struct {
	Details              string   `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendJsonStringResponse) Reset()         { *m = SendJsonStringResponse{} }
func (m *SendJsonStringResponse) String() string { return proto.CompactTextString(m) }
func (*SendJsonStringResponse) ProtoMessage()    {}
func (*SendJsonStringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *SendJsonStringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendJsonStringResponse.Unmarshal(m, b)
}
func (m *SendJsonStringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendJsonStringResponse.Marshal(b, m, deterministic)
}
func (m *SendJsonStringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendJsonStringResponse.Merge(m, src)
}
func (m *SendJsonStringResponse) XXX_Size() int {
	return xxx_messageInfo_SendJsonStringResponse.Size(m)
}
func (m *SendJsonStringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendJsonStringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendJsonStringResponse proto.InternalMessageInfo

func (m *SendJsonStringResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

// Nested messages
type User struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

type User_SetRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Details              []byte   `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_SetRequest) Reset()         { *m = User_SetRequest{} }
func (m *User_SetRequest) String() string { return proto.CompactTextString(m) }
func (*User_SetRequest) ProtoMessage()    {}
func (*User_SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6, 0}
}

func (m *User_SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_SetRequest.Unmarshal(m, b)
}
func (m *User_SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_SetRequest.Marshal(b, m, deterministic)
}
func (m *User_SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_SetRequest.Merge(m, src)
}
func (m *User_SetRequest) XXX_Size() int {
	return xxx_messageInfo_User_SetRequest.Size(m)
}
func (m *User_SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_User_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_User_SetRequest proto.InternalMessageInfo

func (m *User_SetRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User_SetRequest) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

type User_SetResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Details              []byte   `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User_SetResponse) Reset()         { *m = User_SetResponse{} }
func (m *User_SetResponse) String() string { return proto.CompactTextString(m) }
func (*User_SetResponse) ProtoMessage()    {}
func (*User_SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6, 1}
}

func (m *User_SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User_SetResponse.Unmarshal(m, b)
}
func (m *User_SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User_SetResponse.Marshal(b, m, deterministic)
}
func (m *User_SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User_SetResponse.Merge(m, src)
}
func (m *User_SetResponse) XXX_Size() int {
	return xxx_messageInfo_User_SetResponse.Size(m)
}
func (m *User_SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_User_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_User_SetResponse proto.InternalMessageInfo

func (m *User_SetResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *User_SetResponse) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "messages.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "messages.GetResponse")
	proto.RegisterType((*SendJsonRequest)(nil), "messages.SendJsonRequest")
	proto.RegisterType((*SendJsonResponse)(nil), "messages.SendJsonResponse")
	proto.RegisterType((*SendJsonStringRequest)(nil), "messages.SendJsonStringRequest")
	proto.RegisterType((*SendJsonStringResponse)(nil), "messages.SendJsonStringResponse")
	proto.RegisterType((*User)(nil), "messages.User")
	proto.RegisterType((*User_SetRequest)(nil), "messages.User.SetRequest")
	proto.RegisterType((*User_SetResponse)(nil), "messages.User.SetResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x5d, 0x50, 0x84, 0x59, 0xa3, 0xa6, 0x11, 0xc4, 0xc6, 0x44, 0xb2, 0x31, 0x91, 0x83,
	0x29, 0x01, 0x3d, 0x63, 0xa2, 0x24, 0x44, 0x8f, 0xdb, 0x70, 0x31, 0x5e, 0x00, 0xc7, 0x0d, 0x09,
	0x6e, 0xb1, 0xd3, 0xf5, 0x15, 0x7c, 0x0c, 0x5f, 0xd5, 0xb0, 0x4b, 0xe9, 0x82, 0x10, 0x8e, 0xd3,
	0xfe, 0xf3, 0xcd, 0xdf, 0x7f, 0x0a, 0x90, 0x10, 0x6a, 0x31, 0xd3, 0xca, 0x28, 0x56, 0xfe, 0x44,
	0xa2, 0x61, 0x84, 0xc4, 0x2f, 0x23, 0xa5, 0xa2, 0x29, 0xb6, 0xd2, 0xf3, 0x51, 0xf2, 0xd1, 0x22,
	0xa3, 0x93, 0xb1, 0xc9, 0x74, 0xc1, 0x35, 0x40, 0x1f, 0x4d, 0x88, 0x5f, 0x09, 0x92, 0x61, 0x35,
	0x28, 0x0d, 0x08, 0xf5, 0x73, 0xaf, 0xee, 0x35, 0xbc, 0x66, 0x25, 0x5c, 0x54, 0xc1, 0x0d, 0xf8,
	0xa9, 0x8a, 0x66, 0x2a, 0x26, 0x64, 0x75, 0x38, 0xec, 0xa1, 0x19, 0x4e, 0xa6, 0x94, 0xea, 0x8e,
	0x42, 0x5b, 0x06, 0x6f, 0x70, 0x22, 0x31, 0x7e, 0x7f, 0x21, 0x15, 0xef, 0x60, 0xb2, 0xb6, 0x83,
	0x14, 0x1a, 0x5e, 0xd3, 0xef, 0x9c, 0x8b, 0xcc, 0xa9, 0xb0, 0x4e, 0x85, 0x4c, 0x9d, 0x3a, 0xfa,
	0x2d, 0x9c, 0x3a, 0xfa, 0x66, 0x2f, 0x15, 0xa7, 0x6e, 0x43, 0xd5, 0xaa, 0xa5, 0xd1, 0x93, 0x38,
	0xb2, 0x8e, 0xb6, 0xb7, 0x74, 0xa0, 0xb6, 0xde, 0xb2, 0x73, 0xcc, 0x8f, 0x07, 0xfb, 0xf3, 0x27,
	0xf1, 0x2e, 0x80, 0xdc, 0x19, 0x65, 0x1e, 0x54, 0x58, 0xc9, 0x8e, 0x3f, 0x80, 0x2f, 0x73, 0x21,
	0xd7, 0xa0, 0x44, 0x66, 0x68, 0x92, 0x6c, 0x60, 0x39, 0x5c, 0x54, 0xdb, 0x01, 0x9d, 0xdf, 0x02,
	0xf8, 0xf3, 0x29, 0x12, 0xf5, 0xf7, 0x64, 0x8c, 0xec, 0x1e, 0x8a, 0x7d, 0x34, 0xec, 0x4c, 0xd8,
	0xbf, 0x20, 0xdc, 0xaa, 0x79, 0x75, 0xed, 0x34, 0x9b, 0x1a, 0xec, 0xb1, 0x27, 0x28, 0xdb, 0x0c,
	0xd8, 0x85, 0x13, 0xad, 0xad, 0x95, 0xf3, 0x4d, 0x57, 0x4b, 0xc8, 0x00, 0x8e, 0x57, 0x83, 0x64,
	0x57, 0xff, 0xf5, 0x2b, 0x5b, 0xe1, 0x8d, 0xed, 0x82, 0x25, 0xb6, 0x0b, 0x45, 0x89, 0x26, 0x6f,
	0x6b, 0xfe, 0x5e, 0xe1, 0x62, 0xcf, 0xdb, 0x72, 0x57, 0xb6, 0xff, 0xf1, 0xe0, 0xb5, 0xd8, 0x9a,
	0x8d, 0x46, 0xa5, 0xf4, 0x87, 0xdd, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xa6, 0x26, 0x13,
	0x31, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	SendJson(ctx context.Context, in *SendJsonRequest, opts ...grpc.CallOption) (*SendJsonResponse, error)
	SendJsonString(ctx context.Context, in *SendJsonStringRequest, opts ...grpc.CallOption) (*SendJsonStringResponse, error)
	Set(ctx context.Context, in *User_SetRequest, opts ...grpc.CallOption) (*User_SetResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/messages.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendJson(ctx context.Context, in *SendJsonRequest, opts ...grpc.CallOption) (*SendJsonResponse, error) {
	out := new(SendJsonResponse)
	err := c.cc.Invoke(ctx, "/messages.UserService/SendJson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendJsonString(ctx context.Context, in *SendJsonStringRequest, opts ...grpc.CallOption) (*SendJsonStringResponse, error) {
	out := new(SendJsonStringResponse)
	err := c.cc.Invoke(ctx, "/messages.UserService/SendJsonString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Set(ctx context.Context, in *User_SetRequest, opts ...grpc.CallOption) (*User_SetResponse, error) {
	out := new(User_SetResponse)
	err := c.cc.Invoke(ctx, "/messages.UserService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	SendJson(context.Context, *SendJsonRequest) (*SendJsonResponse, error)
	SendJsonString(context.Context, *SendJsonStringRequest) (*SendJsonStringResponse, error)
	Set(context.Context, *User_SetRequest) (*User_SetResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendJsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.UserService/SendJson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendJson(ctx, req.(*SendJsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendJsonString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendJsonStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendJsonString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.UserService/SendJsonString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendJsonString(ctx, req.(*SendJsonStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User_SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.UserService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Set(ctx, req.(*User_SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "SendJson",
			Handler:    _UserService_SendJson_Handler,
		},
		{
			MethodName: "SendJsonString",
			Handler:    _UserService_SendJsonString_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _UserService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
